name: purescript-python
version: 0.1.2.0
github: "purescript-python/purescript-python"
license: LGPL-3
author: "Taine Zhao"
maintainer: "twshere@outlook.com"
copyright: "2020 Taine Zhao"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/purescript-python/purescript-python#readme>

dependencies:
  - aeson >=1.0 && <1.5
  - aeson-better-errors >=0.8
  - aeson-pretty
  - base >=4.11 && <4.13
  - base-compat >=0.6.0
  - bytestring
  - containers
  - directory >=1.2.3
  - filepath
  - monad-control >=1.0.0.0 && <1.1
  - monad-logger >=0.3 && <0.4
  - mtl >=2.1.0 && <2.3.0
  - protolude >=0.1.6 && <0.2.4
  - semigroups >=0.16.2 && <0.19
  - text
  - transformers >=0.3.0 && <0.6
  - transformers-base >=0.4.0 && <0.5
  - transformers-compat >=0.3.0
  - utf8-string >=1 && <2
  - purescript
  - prettyprinter
  - bytestring-conversion
  - utf8-string
  - zip

default-extensions:
  - GADTs
  - ViewPatterns
  - DeriveGeneric
  - DeriveFunctor
  - DeriveTraversable
  - LambdaCase
  - TemplateHaskell
  - DuplicateRecordFields
  - StandaloneDeriving
  - ExistentialQuantification
  - MultiParamTypeClasses
  - NamedFieldPuns
  - PartialTypeSignatures
  - FlexibleInstances
  - ConstraintKinds
  - DataKinds
  - DeriveFoldable
  - DerivingStrategies
  - EmptyDataDecls
  - FlexibleContexts
  - KindSignatures
  - PatternGuards
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections

when:
  - condition: os(darwin)
    then:
      ghc-options: -Wall -O2
      ld-options:
      - -pthread
      - -Wall
    else:
      ghc-options: -Wall -O2 -static
      cc-options: -static
      ld-options:
      - -static
      - -pthread
      - -Wall



library:
  source-dirs: src

executables:
  pspy-blueprint:
    main: Main.hs
    source-dirs: app
    dependencies:
      - purescript-python

tests:
  purescript-python-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - purescript-python
